services:
  db:
    image: postgres:16
    env_file: .env
    ports: ["${POSTGRES_PORT}:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d:ro

  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    ports: ["${PGADMIN_PORT}:80"]
    depends_on: [db]

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: ["start-dev","--http-port","${KEYCLOAK_PORT}"]
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_ENABLED: "true"
    ports: ["${KEYCLOAK_PORT}:${KEYCLOAK_PORT}"]

  backend:
    build: ./backend
    restart: always
    env_file: .env
    ports: ["${API_PORT}:8081"]
    depends_on: [db, keycloak]
    volumes:
      - ./backend/templates:/app/templates:ro

  frontend:
    build: ./frontend
    restart: always
    environment:
      API_URL: http://localhost:${API_PORT}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT: ${KEYCLOAK_CLIENT_FRONTEND}
    ports: ["4200:80"]
    depends_on: [backend, keycloak]

volumes:
  dbdata:
